spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hl7_messaging?serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:Kenan}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: ${DRIVER_CLASS_NAME:com.mysql.jdbc.Driver}
#  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
#  jpa:
#    properties:
#      hibernate:
#        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

# App Properties
bootcamp:
  app:
    jwtCookieName: ${JWT_COOKIE_NAME:HL7_JWT}
    jwtSecret: ${JWT_SECRET:bootcampserapionsecret}
    jwtExpirationMs: ${JWT_EXPIRATION_MS:86400000}

server:
  port: 8123